FROM ruby:slim

# Install git and dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    git \
    build-essential \
    libyaml-dev \
    pkg-config \
    && rm -rf /var/lib/apt/lists/*

# Clone the repository
RUN git clone https://github.com/urbanadventurer/WhatWeb.git /whatweb

# Set directory
WORKDIR /whatweb

# Install dependencies
RUN bundle install

# Set the entrypoint
ENTRYPOINT ["./whatweb"]
