from fpdf import FPDF
from datetime import datetime
import json

class PDFReport(FPDF):
    def header(self):
        # Header on every page
        self.set_font('Arial', 'B', 10)
        self.set_text_color(100, 100, 100)
        self.cell(0, 10, 'CyberRakshak Vulnerability Assessment Report', 0, 0, 'L')
        self.cell(0, 10, f'Page {self.page_no()}', 0, 1, 'R')
        self.line(10, 20, 200, 20)
        self.ln(15)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, 'Confidential - Generated by CyberRakshak', 0, 0, 'C')

def clean_text(text: str) -> str:
    """Sanitizes text for FPDF (Latin-1 encoding) and removes control chars."""
    if not text: return ""
    text = str(text)
    text = "".join(ch for ch in text if ord(ch) >= 32 or ch in "\n\r\t")
    replacements = {
        '\u2013': '-', '\u2014': '-', '\u2018': "'", '\u2019': "'",
        '\u201c': '"', '\u201d': '"', '\u2026': '...'
    }
    for char, replacement in replacements.items():
        text = text.replace(char, replacement)
    return text.encode('latin-1', 'ignore').decode('latin-1')

def get_severity_color(pdf, severity):
    severity = str(severity).lower()
    if severity in ['critical', 'high']:
        pdf.set_text_color(180, 0, 0) # Red
    elif severity == 'medium':
        pdf.set_text_color(200, 100, 0) # Orange
    elif severity == 'low':
        pdf.set_text_color(0, 100, 0) # Green
    else:
        pdf.set_text_color(0, 0, 0) # Black

def draw_section_header(pdf, title):
    pdf.set_font("Arial", "B", 14)
    pdf.set_text_color(0, 51, 102) # Dark Blue
    pdf.cell(0, 10, title, 0, 1, 'L')
    pdf.line(pdf.get_x(), pdf.get_y(), 200, pdf.get_y())
    pdf.ln(5)
    pdf.set_text_color(0, 0, 0)

def resolve_cvss(v):
    """
    Intelligently resolves CVSS score.
    Priority: 
    1. Explicit NVD Score (from Enrichment)
    2. Scanner Provided Score (from Parser)
    3. Estimated Score based on Severity (Fallback)
    """
    scanner_score = v.get('cvss_score')
    
    # Safely access nested dictionary
    enrichment = v.get('enrichment') or {}
    nvd_data = enrichment.get('nvd_data') or {}
    nvd_score = nvd_data.get('score')
    
    s1 = 0.0
    s2 = 0.0
    
    # 1. Check Scanner/NVD
    try: s1 = float(scanner_score) if scanner_score else 0.0
    except: pass
    try: s2 = float(nvd_score) if nvd_score else 0.0
    except: pass
    
    final = max(s1, s2)
    
    if final > 0:
        return str(final)

    # 2. Fallback: Estimate based on Severity string
    sev = str(v.get('severity', '')).lower()
    if sev == 'critical': return "9.5 (Est)"
    if sev == 'high': return "8.0 (Est)"
    if sev == 'medium': return "5.5 (Est)"
    if sev == 'low': return "3.0 (Est)"
    
    return "N/A"

def generate_pdf_report(job_data: dict, filename: str):
    pdf = PDFReport()
    pdf.set_auto_page_break(auto=True, margin=15)
    
    # Extract Data
    target = clean_text(job_data.get('target', 'Unknown'))
    scan_date = str(job_data.get('created_at'))[:19]
    job_id = str(job_data.get('job_id'))
    results = job_data.get("results", {})
    ports = results.get("ports", [])
    vulns = results.get("vulnerabilities", [])
    techs = results.get("technologies", [])
    
    # Sort vulns by severity for the stats
    crit_count = len([v for v in vulns if v.get('severity', '').lower() == 'critical'])
    high_count = len([v for v in vulns if v.get('severity', '').lower() == 'high'])
    med_count = len([v for v in vulns if v.get('severity', '').lower() == 'medium'])
    low_count = len([v for v in vulns if v.get('severity', '').lower() in ['low', 'info', 'unknown']])
    
    overall_risk = "LOW"
    if crit_count > 0: overall_risk = "CRITICAL"
    elif high_count > 0: overall_risk = "HIGH"
    elif med_count > 0: overall_risk = "MEDIUM"

    # ================= PAGE 1: EXECUTIVE SUMMARY =================
    pdf.add_page()
    
    # 1. Title Section
    pdf.set_font("Arial", "B", 20)
    pdf.cell(0, 15, f"Vulnerability Assessment Report", 0, 1, 'C')
    pdf.set_font("Arial", "", 12)
    pdf.cell(0, 8, f"Target: {target}", 0, 1, 'C')
    pdf.cell(0, 8, f"Date: {scan_date} | Job ID: {job_id}", 0, 1, 'C')
    pdf.ln(10)

    # 2. Executive Summary
    draw_section_header(pdf, "Executive Summary")
    pdf.set_font("Arial", "", 11)
    
    pdf.cell(90, 8, f"Total Open Ports: {len(ports)}", 1, 0)
    pdf.cell(90, 8, f"Total Findings: {len(vulns)}", 1, 1)
    
    pdf.cell(40, 8, "Overall Risk: ", 1, 0)
    pdf.set_font("Arial", "B", 11)
    get_severity_color(pdf, overall_risk)
    pdf.cell(50, 8, overall_risk, 1, 1)
    pdf.set_text_color(0, 0, 0)
    pdf.set_font("Arial", "", 11)
    
    pdf.ln(5)
    
    pdf.cell(45, 8, f"Critical: {crit_count}", 1, 0, 'C')
    pdf.cell(45, 8, f"High: {high_count}", 1, 0, 'C')
    pdf.cell(45, 8, f"Medium: {med_count}", 1, 0, 'C')
    pdf.cell(45, 8, f"Low/Info: {low_count}", 1, 1, 'C')
    pdf.ln(10)

    # 3. Asset Information
    draw_section_header(pdf, "Asset & Environment")
    pdf.set_font("Arial", "", 11)
    pdf.cell(50, 8, "IP Address / Host:", 0, 0)
    pdf.cell(0, 8, target, 0, 1)
    
    os_guess = "Unknown"
    for p in ports:
        if 'product' in p and 'os' in str(p.get('product', '')).lower():
             os_guess = clean_text(p.get('product'))
             break
    
    pdf.cell(50, 8, "OS Detected:", 0, 0)
    pdf.cell(0, 8, os_guess, 0, 1)
    
    pdf.cell(50, 8, "Technologies:", 0, 0)
    tech_str = ", ".join([t.get('name', '') for t in techs]) if techs else "None detected"
    pdf.multi_cell(0, 8, clean_text(tech_str))
    pdf.ln(5)

    # ================= PAGE 2: PORTS =================
    pdf.add_page()
    draw_section_header(pdf, "Open Ports & Services")
    
    pdf.set_font("Arial", "B", 10)
    pdf.set_fill_color(240, 240, 240)
    pdf.cell(20, 8, "Port", 1, 0, 'C', True)
    pdf.cell(25, 8, "Protocol", 1, 0, 'C', True)
    pdf.cell(60, 8, "Service", 1, 0, 'L', True)
    pdf.cell(85, 8, "Version / Product", 1, 1, 'L', True)
    
    pdf.set_font("Arial", "", 9)
    for p in ports:
        pdf.cell(20, 7, str(p.get('port')), 1, 0, 'C')
        pdf.cell(25, 7, str(p.get('protocol')), 1, 0, 'C')
        pdf.cell(60, 7, clean_text(str(p.get('service'))[:30]), 1, 0, 'L')
        pdf.cell(85, 7, clean_text(str(p.get('product', '') + ' ' + p.get('version', ''))[:45]), 1, 1, 'L')
    pdf.ln(10)

    # ================= VULNERABILITIES =================
    pdf.add_page()
    draw_section_header(pdf, "Detailed Vulnerability Findings")
    
    # Sort vulns: Critical -> High -> Medium -> Low
    severity_order = {'critical': 0, 'high': 1, 'medium': 2, 'low': 3, 'info': 4, 'unknown': 5}
    sorted_vulns = sorted(vulns, key=lambda x: severity_order.get(x.get('severity', 'unknown').lower(), 5))

    if not sorted_vulns:
        pdf.cell(0, 10, "No vulnerabilities detected.", 0, 1)
    
    for v in sorted_vulns:
        _print_standard_vuln_block(pdf, v)

    pdf.output(filename)
    return filename

def _print_standard_vuln_block(pdf, v):
    """Helper to print a detailed vulnerability block."""
    title = clean_text(v.get('title', 'Unknown Finding'))
    sev = clean_text(v.get('severity', 'info')).upper()
    tool = clean_text(v.get('tool', 'Scanner')).upper()
    
    # Header Row with Color
    pdf.set_font("Arial", "B", 11)
    get_severity_color(pdf, sev)
    pdf.cell(150, 8, f"[{sev}] {title}", 0, 0, 'L')
    pdf.set_text_color(100, 100, 100)
    pdf.set_font("Arial", "", 9)
    pdf.cell(40, 8, f"Source: {tool}", 0, 1, 'R')
    pdf.set_text_color(0, 0, 0)
    
    # Metadata Row (CVSS, Port)
    pdf.set_font("Arial", "B", 9)
    cvss = resolve_cvss(v)
    
    pdf.cell(20, 6, "CVSS:", 0, 0)
    pdf.set_font("Arial", "", 9)
    pdf.cell(20, 6, cvss, 0, 0)
    
    pdf.set_font("Arial", "B", 9)
    pdf.cell(20, 6, "Port:", 0, 0)
    pdf.set_font("Arial", "", 9)
    pdf.cell(20, 6, clean_text(str(v.get('port', 'N/A'))), 0, 0)

    # --- CVE & EXPLOIT SECTION ---
    # Get CVE (Prioritize Enrichment -> Scanner -> N/A)
    enrichment = v.get('enrichment') or {}
    cve = v.get('cve') or enrichment.get('cve_id') or "N/A"
    
    # Print CVE Line
    pdf.set_font("Arial", "B", 9)
    pdf.cell(20, 6, "CVE:", 0, 0)
    pdf.set_font("Arial", "", 9)
    pdf.cell(40, 6, clean_text(cve), 0, 0)
    
    pdf.ln(6)

    # === THREAT INTELLIGENCE (Exploits) ===
    has_intel = False

    # Check for Exploits IF we have a valid CVE
    if cve and cve.startswith("CVE-"):
        exploit_info = enrichment.get('exploit_info')
        
        if exploit_info and exploit_info.get('available'):
            has_intel = True
            pdf.set_font("Arial", "B", 9)
            pdf.set_text_color(220, 20, 60) # Crimson Red
            ids = ", ".join(exploit_info.get('ids', []))
            pdf.cell(0, 6, f"!! PUBLIC EXPLOIT AVAILABLE (ExploitDB IDs: {ids})", 0, 1)
        else:
            # Explicitly state no exploit is available
            has_intel = True
            pdf.set_font("Arial", "I", 9)
            pdf.set_text_color(80, 80, 80) # Dark Gray
            pdf.cell(0, 6, "No exploit available in public data base try with CyRa", 0, 1)

    # 2. AlienVault OTX Insights
    otx_data = enrichment.get('otx_data')
    if otx_data:
        has_intel = True
        pdf.set_font("Arial", "B", 9)
        pdf.set_text_color(255, 140, 0) # Dark Orange
        pulses = otx_data.get('pulse_count', 0)
        tags_list = otx_data.get('tags', [])[:5]
        tags_str = ", ".join(tags_list)
        pdf.cell(0, 6, f"[Threat Intel] AlienVault OTX: Found in {pulses} Pulses (Tags: {tags_str})", 0, 1)

    # Reset text color
    pdf.set_text_color(0, 0, 0)
    if has_intel: pdf.ln(2)

    # Description
    pdf.set_font("Arial", "B", 9)
    pdf.cell(0, 6, "Description:", 0, 1)
    pdf.set_font("Arial", "", 9)
    
    # Safe Description Access
    nvd_data = enrichment.get('nvd_data') or {}
    desc = v.get('description') or nvd_data.get('description') or 'No description provided.'
    
    # HTML Cleaning
    desc = clean_text(desc).replace('<p>', '').replace('</p>', '').replace('<b>', '').replace('</b>', '')
    pdf.multi_cell(0, 5, desc)
    
    # Remediation
    pdf.ln(2)
    pdf.set_font("Arial", "B", 9)
    pdf.cell(0, 6, "Remediation / Fix:", 0, 1)
    pdf.set_font("Arial", "", 9)
    sol = clean_text(v.get('solution') or v.get('remediation', 'Apply latest patches and configuration best practices.'))
    pdf.multi_cell(0, 5, sol)
    
    # Separator
    pdf.set_draw_color(200, 200, 200)
    pdf.line(10, pdf.get_y()+5, 200, pdf.get_y()+5)
    pdf.ln(8)
