from fpdf import FPDF
from datetime import datetime
import json

class PDFReport(FPDF):
    def header(self):
        # Header on every page
        self.set_font('Arial', 'B', 10)
        self.set_text_color(100, 100, 100)
        self.cell(0, 10, 'CyberRakshak Vulnerability Assessment Report', 0, 0, 'L')
        self.cell(0, 10, f'Page {self.page_no()}', 0, 1, 'R')
        self.line(10, 20, 200, 20)
        self.ln(15)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, 'Confidential - Generated by CyberRakshak', 0, 0, 'C')

def clean_text(text: str) -> str:
    """Sanitizes text for FPDF (Latin-1 encoding) and removes control chars."""
    if not text: return ""
    text = "".join(ch for ch in text if ord(ch) >= 32 or ch in "\n\r\t")
    replacements = {
        '\u2013': '-', '\u2014': '-', '\u2018': "'", '\u2019': "'",
        '\u201c': '"', '\u201d': '"', '\u2026': '...'
    }
    for char, replacement in replacements.items():
        text = text.replace(char, replacement)
    return text.encode('latin-1', 'ignore').decode('latin-1')

def get_severity_color(pdf, severity):
    severity = severity.lower()
    if severity in ['critical', 'high']:
        pdf.set_text_color(180, 0, 0) # Red
    elif severity == 'medium':
        pdf.set_text_color(200, 100, 0) # Orange
    elif severity == 'low':
        pdf.set_text_color(0, 100, 0) # Green
    else:
        pdf.set_text_color(0, 0, 0) # Black

def draw_section_header(pdf, title):
    pdf.set_font("Arial", "B", 14)
    pdf.set_text_color(0, 51, 102) # Dark Blue
    pdf.cell(0, 10, title, 0, 1, 'L')
    pdf.line(pdf.get_x(), pdf.get_y(), 200, pdf.get_y())
    pdf.ln(5)
    pdf.set_text_color(0, 0, 0)

def group_nikto_findings(vulns):
    """Combines repetitive Nikto header missing issues."""
    grouped = []
    header_issues = []
    
    for v in vulns:
        title = v.get('title', '').lower()
        if 'header' in title and ('missing' in title or 'not set' in title or 'anti-clickjacking' in title):
            header_issues.append(v)
        else:
            grouped.append(v)
            
    if header_issues:
        grouped.append({
            'tool': 'nikto',
            'severity': 'low',
            'title': f"Multiple Missing Security Headers ({len(header_issues)} headers)",
            'description': "Several HTTP security headers are missing from the web server response. \n" + 
                           "\n".join([f"- {clean_text(h.get('title'))}" for h in header_issues]),
            'solution': "Configure the web server to send strict security headers (e.g., X-Frame-Options, X-Content-Type-Options, CSP).",
            'cvss_score': 'N/A'
        })
    return grouped

def generate_pdf_report(job_data: dict, filename: str):
    pdf = PDFReport()
    pdf.set_auto_page_break(auto=True, margin=15)
    
    # Extract Data
    target = clean_text(job_data.get('target', 'Unknown'))
    scan_date = str(job_data.get('created_at'))[:19]
    job_id = str(job_data.get('job_id'))
    results = job_data.get("results", {})
    ports = results.get("ports", [])
    vulns = results.get("vulnerabilities", [])
    techs = results.get("technologies", [])
    
    # Calculate Stats
    crit_count = len([v for v in vulns if v.get('severity') in ['critical']])
    high_count = len([v for v in vulns if v.get('severity') in ['high']])
    med_count = len([v for v in vulns if v.get('severity') in ['medium']])
    low_count = len([v for v in vulns if v.get('severity') in ['low', 'info', 'unknown']])
    
    overall_risk = "LOW"
    if crit_count > 0: overall_risk = "CRITICAL"
    elif high_count > 0: overall_risk = "HIGH"
    elif med_count > 0: overall_risk = "MEDIUM"

    # ================= PAGE 1: EXECUTIVE SUMMARY =================
    pdf.add_page()
    
    # 1. Title Section
    pdf.set_font("Arial", "B", 20)
    pdf.cell(0, 15, f"Vulnerability Assessment Report", 0, 1, 'C')
    pdf.set_font("Arial", "", 12)
    pdf.cell(0, 8, f"Target: {target}", 0, 1, 'C')
    pdf.cell(0, 8, f"Date: {scan_date} | Job ID: {job_id}", 0, 1, 'C')
    pdf.ln(10)

    # 2. Executive Summary
    draw_section_header(pdf, "Executive Summary")
    pdf.set_font("Arial", "", 11)
    
    # Grid layout for stats
    pdf.cell(90, 8, f"Total Open Ports: {len(ports)}", 1, 0)
    pdf.cell(90, 8, f"Total Services: {len(ports)}", 1, 1) # Usually mapping 1:1 for basic scans
    pdf.cell(90, 8, f"Total Vulnerabilities: {len(vulns)}", 1, 0)
    
    # Risk Rating with color
    pdf.cell(40, 8, "Overall Risk: ", 1, 0)
    pdf.set_font("Arial", "B", 11)
    get_severity_color(pdf, overall_risk)
    pdf.cell(50, 8, overall_risk, 1, 1)
    pdf.set_text_color(0, 0, 0)
    pdf.set_font("Arial", "", 11)
    
    pdf.ln(5)
    
    # Vuln Counts
    pdf.cell(45, 8, f"Critical: {crit_count}", 1, 0, 'C')
    pdf.cell(45, 8, f"High: {high_count}", 1, 0, 'C')
    pdf.cell(45, 8, f"Medium: {med_count}", 1, 0, 'C')
    pdf.cell(45, 8, f"Low/Info: {low_count}", 1, 1, 'C')
    pdf.ln(10)

    # 3. Asset Information
    draw_section_header(pdf, "Asset & Environment Information")
    pdf.set_font("Arial", "", 11)
    pdf.cell(50, 8, "IP Address / Host:", 0, 0)
    pdf.cell(0, 8, target, 0, 1)
    
    # Try to find OS from Nmap ports (generic heuristic) or techs
    os_guess = "Unknown"
    for p in ports:
        if 'product' in p and 'os' in str(p.get('product', '')).lower():
             os_guess = clean_text(p.get('product'))
             break
    
    pdf.cell(50, 8, "OS Detected:", 0, 0)
    pdf.cell(0, 8, os_guess, 0, 1)
    
    pdf.cell(50, 8, "Technologies:", 0, 0)
    tech_str = ", ".join([t.get('name', '') for t in techs]) if techs else "None detected"
    pdf.multi_cell(0, 8, clean_text(tech_str))
    pdf.ln(5)


    # ================= PAGE 2: PORTS & VULN GROUPS =================
    pdf.add_page()
    
    # 4. Open Ports Table
    draw_section_header(pdf, "Open Ports & Services")
    
    pdf.set_font("Arial", "B", 10)
    pdf.set_fill_color(240, 240, 240)
    pdf.cell(20, 8, "Port", 1, 0, 'C', True)
    pdf.cell(25, 8, "Protocol", 1, 0, 'C', True)
    pdf.cell(60, 8, "Service", 1, 0, 'L', True)
    pdf.cell(85, 8, "Version / Product", 1, 1, 'L', True)
    
    pdf.set_font("Arial", "", 9)
    for p in ports:
        pdf.cell(20, 7, str(p.get('port')), 1, 0, 'C')
        pdf.cell(25, 7, str(p.get('protocol')), 1, 0, 'C')
        pdf.cell(60, 7, clean_text(str(p.get('service'))[:30]), 1, 0, 'L')
        pdf.cell(85, 7, clean_text(str(p.get('product', '') + ' ' + p.get('version', ''))[:45]), 1, 1, 'L')
    pdf.ln(10)

    # ================= VULNERABILITY GROUPS =================
    
    # Categorize Vulns
    openvas_vulns = [v for v in vulns if v.get('tool') == 'openvas']
    zap_vulns = [v for v in vulns if v.get('tool') == 'zap']
    nikto_vulns = group_nikto_findings([v for v in vulns if v.get('tool') == 'nikto'])
    
    # Group remaining (Nuclei, Nmap, etc) as Infrastructure
    infra_vulns = [v for v in vulns if v.get('tool') not in ['openvas', 'zap', 'nikto']]

    # --- Group 1: OpenVAS ---
    if openvas_vulns:
        pdf.add_page()
        draw_section_header(pdf, "Group 1: OpenVAS Findings")
        
        # Headers
        pdf.set_font("Arial", "B", 9)
        pdf.set_fill_color(230, 230, 250)
        pdf.cell(25, 8, "Severity", 1, 0, 'C', True)
        pdf.cell(90, 8, "Vulnerability Title", 1, 0, 'L', True)
        pdf.cell(20, 8, "CVSS", 1, 0, 'C', True)
        pdf.cell(25, 8, "Port", 1, 0, 'C', True)
        pdf.cell(30, 8, "CPE", 1, 1, 'L', True)
        
        pdf.set_font("Arial", "", 9)
        for v in openvas_vulns:
            sev = clean_text(v.get('severity', 'info'))
            get_severity_color(pdf, sev)
            pdf.cell(25, 6, sev.upper(), 1, 0, 'C')
            pdf.set_text_color(0, 0, 0)
            
            pdf.cell(90, 6, clean_text(v.get('title'))[:50], 1, 0, 'L')
            
            # Handle CVSS safely
            raw_cvss = v.get('cvss_score') or v.get('enrichment', {}).get('nvd_data', {}).get('score')
            cvss = clean_text(str(raw_cvss) if raw_cvss is not None else 'N/A')
            pdf.cell(20, 6, cvss, 1, 0, 'C')
            
            pdf.cell(25, 6, clean_text(v.get('port')), 1, 0, 'C')
            pdf.cell(30, 6, "N/A", 1, 1, 'L') # CPE often missing in basic parsing, keeping placeholder
            
            # Optional: Add description row if critical
            if sev.lower() in ['critical', 'high']:
                pdf.set_font("Arial", "I", 8)
                pdf.cell(190, 5, "Desc: " + clean_text(v.get('description', ''))[:130] + "...", "LRB", 1, 'L')
                pdf.set_font("Arial", "", 9)

    # --- Group 2: Infrastructure / Network (Nuclei, Nmap) ---
    if infra_vulns:
        pdf.add_page()
        draw_section_header(pdf, "Group 2: Infrastructure & Network Findings")
        
        for v in infra_vulns:
            _print_standard_vuln_block(pdf, v)

    # --- Group 3: Nikto Findings ---
    if nikto_vulns:
        pdf.add_page()
        draw_section_header(pdf, "Group 3: Nikto Web Server Findings")
        pdf.set_font("Arial", "I", 10)
        pdf.cell(0, 8, "Issues related to Web Server misconfigurations (e.g., Headers, Outdated Software).", 0, 1)
        pdf.ln(2)
        
        for v in nikto_vulns:
            _print_standard_vuln_block(pdf, v)

    # --- Group 4: OWASP ZAP Findings ---
    if zap_vulns:
        pdf.add_page()
        draw_section_header(pdf, "Group 4: OWASP ZAP Web Application Findings")
        
        for v in zap_vulns:
            _print_standard_vuln_block(pdf, v)

    pdf.output(filename)
    return filename

def _print_standard_vuln_block(pdf, v):
    """Helper to print a detailed vulnerability block for Groups 2, 3, 4."""
    title = clean_text(v.get('title', 'Unknown'))
    sev = clean_text(v.get('severity', 'info')).upper()
    
    # Title Row
    pdf.set_font("Arial", "B", 11)
    get_severity_color(pdf, sev)
    pdf.cell(190, 8, f"[{sev}] {title}", 0, 1, 'L')
    pdf.set_text_color(0, 0, 0)
    
    # Metadata
    pdf.set_font("Arial", "B", 9)
    raw_cvss = v.get('cvss_score') or v.get('enrichment', {}).get('nvd_data', {}).get('score')
    cvss = clean_text(str(raw_cvss) if raw_cvss is not None else 'N/A')
    
    pdf.cell(20, 6, "CVSS:", 0, 0)
    pdf.set_font("Arial", "", 9)
    pdf.cell(20, 6, cvss, 0, 0)
    
    pdf.set_font("Arial", "B", 9)
    pdf.cell(20, 6, "Port:", 0, 0)
    pdf.set_font("Arial", "", 9)
    pdf.cell(20, 6, clean_text(str(v.get('port'))), 0, 1)
    
    # Description
    pdf.set_font("Arial", "B", 9)
    pdf.cell(0, 6, "Description:", 0, 1)
    pdf.set_font("Arial", "", 9)
    desc = clean_text(v.get('description', 'No description provided.')).replace('<p>', '').replace('</p>', '')
    pdf.multi_cell(0, 5, desc)
    
    # Remediation
    pdf.ln(2)
    pdf.set_font("Arial", "B", 9)
    pdf.cell(0, 6, "Remediation / Fix:", 0, 1)
    pdf.set_font("Arial", "", 9)
    sol = clean_text(v.get('solution') or v.get('remediation', 'Apply latest patches and configuration best practices.'))
    pdf.multi_cell(0, 5, sol)
    
    pdf.line(10, pdf.get_y()+5, 200, pdf.get_y()+5)
    pdf.ln(8)
